
compositions:

  - name: system-base
    version: 1.0.0
    body: |
      deployments:
      - name: cert-manager
        composition:
          name: cert/cert-manager
          version: 1.0.0

      - name: ingress
        composition:
          name: ingress
          version: 1.0.0


